### PR TITLE
Html5

### LINKED ISSUE #57: HTML directives with dashes do not highlight correctly
screenshot 2015-01-08 17 34 41

I expected it to look like:

screenshot 2015-01-08 17 35 49

With the blue braces around the arguments parenthesis

### PR DESCRIPTION
**Pull request by geigerzaehler**
Recognizes tags and attributes containing dashes.

Fixes #57.

### CODE REVIEW

**Comment by digitaltoad** [comment]
Something strange that happens with these changes. Any tag level text is highlighted as a tag. This doesn’t seem right to me.


—
Josh

**Comment by geigerzaehler** [comment]
> Any tag level text is highlighted as a tag. This doesn’t seem right to me.

Yes that is the intention. HTML5 allows [arbitrary tag names](http://www.html5rocks.com/en/tutorials/webcomponents/customelements/). Since the syntax is supposed to highlight the structure it makes sense, in my oppinion, to highlight ever tag.

**Comment by digitaltoad** [comment]
There seems to be a dash requirement for custom tags. This should probably be part of the highlighting. We should trigger the highlight if a dash is found instead of highlighting everything.

**Comment by Gorgoroth** [comment]
That is true, [source](http://w3c.github.io/webcomponents/spec/custom/#concepts).

Even though the new HTML5 elements are not highlighted:
* article
* aside
* audio
* bdi
* canvas
* command
* datalist
* details
* embed
* figcaption
* figure
* footer
* header
* hgroup
* keygen
* mark
* meter
* nav
* output
* progress
* rp
* rt
* ruby
* section
* source
* summary
* time
* track
* video
* wbr

Taken from [here](http://www.w3.org/TR/html-markup/elements.html), with "New"-Tag.

**Comment by digitaltoad** [comment]
Using https://github.com/othree/html5.vim makes this automatic.

**Pull request closed without merging**
